


export const countryNames = [
['Afghanistan', 'Afghanistan'],
['Albania', 'Albania'],
['Algeria', 'Algeria'],
['Andorra', 'Andorra'],
['Angola', 'Angola'],
['Anguilla', 'Anguilla'],
['Antigua and Barbuda', 'Antigua and Barbuda'],
['Argentina', 'Argentina'],
['Armenia', 'Armenia'],
['Aruba', 'Aruba'],
['Australia', 'Australia'],
['Austria', 'Austria'],
['Azerbaijan', 'Azerbaijan'],
['Bahamas', 'Bahamas'],
['Bahrain', 'Bahrain'],
['Bangladesh', 'Bangladesh'],
['Barbados', 'Barbados'],
['Belarus', 'Belarus'],
['Belgium', 'Belgium'],
['Belize', 'Belize'],
['Benin', 'Benin'],
['Bermuda', 'Bermuda'],
['Bhutan', 'Bhutan'],
['Bolivia', 'Bolivia'],
['Bosnia and Herzegovina', 'Bosnia and Herzegovina'],
['Botswana', 'Botswana'],
['Brazil', 'Brazil'],
['British Virgin Islands', 'VG'],
['Brunei', 'Brunei'],
['Bulgaria', 'Bulgaria'],
['Burkina Faso', 'Burkina Faso'],
['Burundi', 'Burundi'],
['CAR', 'CF'],
['Cabo Verde', 'CV'],
['Cambodia', 'Cambodia'],
['Cameroon', 'Cameroon'],
['Canada', 'Canada'],
['Caribbean Netherlands', 'BQ'],
['Cayman Islands', 'Cayman Islands'],
['Chad', 'Chad'],
['Channel Islands', 'GB'],
['Chile', 'Chile'],
['China', 'China'],
['Colombia', 'Colombia'],
['Comoros', 'Comoros'],
['Congo', 'CG'],
['Cook Islands', 'Cook Islands'],
['Costa Rica', 'Costa Rica'],
['Croatia', 'Croatia'],
['Cuba', 'Cuba'],
['Curaçao', 'CW'],
['Cyprus', 'Cyprus'],
['Czechia', 'CZ'],
['DPRK', 'KP'],
['DRC', 'CD'],
['Denmark', 'Denmark'],
['Diamond Princess', 'Diamond Princess'],
['Djibouti', 'DJ'],
['Dominica', 'Dominica'],
['Dominican Republic', 'Dominican Republic'],
['Ecuador', 'Ecuador'],
['Egypt', 'Egypt'],
['El Salvador', 'El Salvador'],
['Equatorial Guinea', 'Equatorial Guinea'],
['Eritrea', 'Eritrea'],
['Estonia', 'Estonia'],
['Eswatini', 'SZ'],
['Ethiopia', 'Ethiopia'],
['Faeroe Islands', 'FO'],
['Falkland Islands', 'FK'],
['Fiji', 'Fiji'],
['Finland', 'Finland'],
['France', 'France'],
['French Guiana', 'GF'],
['French Polynesia', 'PF'],
['Gabon', 'Gabon'],
['Gambia', 'Gambia'],
['Georgia', 'Georgia'],
['Germany', 'Germany'],
['Ghana', 'Ghana'],
['Gibraltar', 'Gibraltar'],
['Greece', 'Greece'],
['Greenland', 'Greenland'],
['Grenada', 'Grenada'],
['Guadeloupe', 'Guadeloupe'],
['Guatemala', 'Guatemala'],
['Guinea', 'Guinea'],
['Guinea-Bissau', 'Guinea-Bissau'],
['Guyana', 'Guyana'],
['Haiti', 'Haiti'],
['Honduras', 'Honduras'],
['Hong Kong', 'Hong Kong'],
['Hungary', 'Hungary'],
['Iceland', 'Iceland'],
['India', 'India'],
['Indonesia', 'Indonesia'],
['Iran', 'Iran'],
['Iraq', 'Iraq'],
['Ireland', 'Ireland'],
['Isle of Man', 'Isle of Man'],
['Israel', 'Israel'],
['Italy', 'Italy'],
['Ivory Coast', 'Ivory Coast'],
['Jamaica', 'Jamaica'],
['Japan', 'Japan'],
['Jordan', 'Jordan'],
['Kazakhstan', 'Kazakhstan'],
['Kenya', 'Kenya'],
['Kiribati', 'Kiribati'],
['Kuwait', 'Kuwait'],
['Kyrgyzstan', 'Kyrgyzstan'],
['Laos', 'Laos'],
['Latvia', 'Latvia'],
['Lebanon', 'Lebanon'],
['Lesotho', 'Lesotho'],
['Liberia', 'Liberia'],
['Libya', 'Libya'],
['Liechtenstein', 'Liechtenstein'],
['Lithuania', 'Lithuania'],
['Luxembourg', 'Luxembourg'],
['MS Zaandam', 'MM'],
['Macao', 'Macao'],
['Madagascar', 'Madagascar'],
['Malawi', 'Malawi'],
['Malaysia', 'Malaysia'],
['Maldives', 'Maldives'],
['Mali', 'Mali'],
['Malta', 'Malta'],
['Marshall Islands', 'Marshall Islands'],
['Martinique', 'Martinique'],
['Mauritania', 'Mauritania'],
['Mauritius', 'Mauritius'],
['Mayotte', 'Mayotte'],
['Mexico', 'Mexico'],
['Micronesia', 'Micronesia'],
['Moldova', 'Moldova'],
['Monaco', 'Monaco'],
['Mongolia', 'Mongolia'],
['Montenegro', 'Montenegro'],
['Montserrat', 'Montserrat'],
['Morocco', 'Morocco'],
['Mozambique', 'Mozambique'],
['Myanmar', 'Myanmar'],
['Namibia', 'Namibia'],
['Nauru', 'Nauru'],
['Nepal', 'Nepal'],
['Netherlands', 'Netherlands'],
['New Caledonia', 'New Caledonia'],
['New Zealand', 'New Zealand'],
['Nicaragua', 'Nicaragua'],
['Niger', 'Niger'],
['Nigeria', 'Nigeria'],
['Niue', 'Niue'],
['North Macedonia', 'MK'],
['Norway', 'Norway'],
['Oman', 'Oman'],
['Pakistan', 'Pakistan'],
['Palau', 'Palau'],
['Palestine', 'PS'],
['Panama', 'Panama'],
['Papua New Guinea', 'Papua New Guinea'],
['Paraguay', 'Paraguay'],
['Peru', 'Peru'],
['Philippines', 'Philippines'],
['Poland', 'Poland'],
['Portugal', 'Portugal'],
['Qatar', 'Qatar'],
['Romania', 'Romania'],
['Russia', 'Russia'],
['Rwanda', 'Rwanda'],
['Réunion', 'RE'],
['S. Korea', 'KR'],
['Saint Helena', 'SH'],
['Saint Kitts and Nevis', 'KN'],
['Saint Lucia', 'LC'],
['Saint Martin', 'MF'],
['Saint Pierre Miquelon', 'PM'],
['Samoa', 'Samoa'],
['San Marino', 'San Marino'],
['Sao Tome and Principe', 'Sao Tome and Principe'],
['Saudi Arabia', 'Saudi Arabia'],
['Senegal', 'Senegal'],
['Serbia', 'Serbia'],
['Seychelles', 'Seychelles'],
['Sierra Leone', 'Sierra Leone'],
['Singapore', 'Singapore'],
['Sint Maarten', 'SX'],
['Slovakia', 'Slovakia'],
['Slovenia', 'Slovenia'],
['Solomon Islands', 'Solomon Islands'],
['Somalia', 'Somalia'],
['South Africa', 'South Africa'],
['South Sudan', 'SS'],
['Spain', 'Spain'],
['Sri Lanka', 'Sri Lanka'],
['St. Barth', 'BL'],
['St. Vincent Grenadines', 'VC'],
['Sudan', 'Sudan'],
['Suriname', 'Suriname'],
['Sweden', 'Sweden'],
['Switzerland', 'Switzerland'],
['Syria', 'Syria'],
['Taiwan', 'Taiwan'],
['Tajikistan', 'Tajikistan'],
['Tanzania', 'Tanzania'],
['Thailand', 'Thailand'],
['Timor-Leste', 'TL'],
['Togo', 'TG'],
['Tonga', 'Tonga'],
['Trinidad and Tobago', 'Trinidad and Tobago'],
['Tunisia', 'Tunisia'],
['Turkey', 'Turkey'],
['Turks and Caicos', 'TC'],
['Tuvalu', 'Tuvalu'],
['UAE', 'AE'],
['UK', 'GB'],
['USA', 'US'],
['Uganda', 'Uganda'],
['Ukraine', 'Ukraine'],
['Uruguay', 'Uruguay'],
['Uzbekistan', 'Uzbekistan'],
['Vanuatu', 'Vanuatu'],
['Vatican City', 'VA'],
['Venezuela', 'Venezuela'],
['Vietnam', 'Vietnam'],
['Wallis and Futuna', 'WF'],
['Western Sahara', 'EH'],
['Yemen', 'Yemen'],
['Zambia', 'Zambia'],
['Zimbabwe', 'Zimbabwe']]

export const countries = countryNames.map(country => {
    return {api:country[0], map:country[1]} 
})