# Generated by Django 4.0.6 on 2022-07-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('last_update', models.DateTimeField()),
                ('active_cases', models.JSONField()),
                ('new_cases', models.JSONField()),
                ('new_death', models.JSONField()),
                ('total_cases', models.JSONField()),
                ('total_death', models.JSONField()),
                ('total_recovered', models.JSONField()),
            ],
        ),
    ]
