# Generated by Django 4.0.6 on 2022-07-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_update',
            field=models.CharField(max_length=50),
        ),
    ]
